### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by kavvano** [kavvano/furima-29818#9]
### 自身のフリマアプリのURL
https://furima-29818.herokuapp.com/

### Basic認証のIDとパスワード
ユーザー名：admin
パスワード：2222

### 出品者用のメールアドレスとパスワード
メールアドレス：take@gmail.com
パスワード：take30

### 購入者用のメールアドレスとパスワード
メールアドレス：tako@gmail.com
パスワード：tako30

### 購入用カードの番号・期限・セキュリティコード
クレジットカード番号：4242424242424242
有効期限：2024年3月
セキュリティコード：123

ご確認をお願いいたします。

**Comment by ryszw** [comment]
河野さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
